spring:
  application:
    name: backend
  mvc:
    async:
      request-timeout: 3600000
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:sqlite:pantheon.db?foreign_keys=on
    driver-class-name: org.sqlite.JDBC
    username:
    password:

  flyway:
    url: jdbc:sqlite:pantheon.db?foreign_keys=on
    enabled: true
    validate-on-migrate: false
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

app:
  sse:
    batch:
      size: 50
    timeout: 0
